SHELL = /bin/sh

# Compiler
CC = g++

# Compiler flags
CFLAGS = -Wall

all:

clean:
	rm lab9 lab10 lab11 lab12 lab13 lab14

lab9:
	$(CC) $(CFLAGS) lab9.cpp -o lab9

lab10:
	$(CC) $(CFLAGS) lab10.cpp -o lab10

lab11:
	$(CC) $(CFLAGS) lab11.cpp -o lab11

lab12:
	$(CC) $(CFLAGS) lab12.cpp -o lab12

lab13:
	$(CC) $(CFLAGS) lab13.cpp -o lab13

lab14:
	$(CC) $(CFLAGS) lab14.cpp -o lab14
