SHELL = /bin/sh

# Compiler
CC = g++

# Compiler flags
CFLAGS1 = -Wall
CFLAGS2 = -lncurses

all:

clean:
	rm lab1 lab2 lab3 lab4 lab5 lab6 lab7 lab8

lab1:
	$(CC) $(CFLAGS1) lab1.cpp -o lab1

lab2:
	$(CC) $(CFLAGS1) lab2.cpp -o lab2

lab3:
	$(CC) $(CFLAGS1) lab3.cpp -o lab3

lab4:
	$(CC) $(CFLAGS1) lab4.cpp -o lab4

lab5:
	$(CC) $(CFLAGS1) $(CFLAGS2) lab5.cpp -o lab5

lab6:
	$(CC) $(CFLAGS1) lab6.cpp -o lab6

lab7:
	$(CC) $(CFLAGS1) lab7.cpp -o lab7

lab8:
	$(CC) $(CFLAGS1) lab8.cpp -o lab8
