SHELL = /bin/sh

# Compiler
CC = g++

# Compiler flags
CFLAGS1 = -Wall

all:

clean:
	rm l1 l2 l3 l4 l5 l6 l7 l8 l9 l10 l11 l12 l13

l1:
	$(CC) $(CFLAGS1) l1.cpp -o l1

l2:
	$(CC) $(CFLAGS1) l2.cpp -o l2

l3:
	$(CC) $(CFLAGS1) l3.cpp -o l3

l4:
	$(CC) $(CFLAGS1) l4.cpp -o l4

l5:
	$(CC) $(CFLAGS1) l5.cpp -o l5

l6:
	$(CC) $(CFLAGS1) l6.cpp -o l6

l7:
	$(CC) $(CFLAGS1) l7.cpp -o l7

l8:
	$(CC) $(CFLAGS1) l8.cpp -o l8

l9:
	$(CC) $(CFLAGS1) l9.cpp -o l9
	
l10:
	$(CC) $(CFLAGS1) l10.cpp -o l10
	
l11:
	$(CC) $(CFLAGS1) l11.cpp -o l11
	
l12:
	$(CC) $(CFLAGS1) l12.cpp -o l12
	
l13:
	$(CC) $(CFLAGS1) l13.cpp -o l13
	
l14:
	$(CC) $(CFLAGS1) l14.cpp -o l14
