SHELL = /bin/sh

# Compiler
CC = g++

# Compiler flags
CFLAGS = -Wall

all:

clean:
	rm work9 work10 work11 work12 work13 work14 work15

work9:
	$(CC) $(CFLAGS) work9.cpp -o work9

work10:
	$(CC) $(CFLAGS) work10.cpp -o work10

work11:
	$(CC) $(CFLAGS) work11.cpp -o work11

work12:
	$(CC) $(CFLAGS) work12.cpp -o work12

work13:
	$(CC) $(CFLAGS) work13.cpp -o work13

work14:
	$(CC) $(CFLAGS) work14.cpp -o work14

work15:
	$(CC) $(CFLAGS) work15.cpp -o work15
