SHELL = /bin/sh

# Compiler
CC = g++

# Compiler flags
CFLAGS1 = -Wall

all:

clean:
	rm work9 work10 work11 work12 work13 work14 work15

work9:
	$(CC) $(CFLAGS1) work1.cpp -o work9

work10:
	$(CC) $(CFLAGS1) work2.cpp -o work10

work11:
	$(CC) $(CFLAGS1) work3.cpp -o work11

work12:
	$(CC) $(CFLAGS1) work4.cpp -o work12

work13:
	$(CC) $(CFLAGS1) work5.cpp -o work13

work14:
	$(CC) $(CFLAGS1) work6.cpp -o work14

work15:
	$(CC) $(CFLAGS1) work7.cpp -o work15
