SHELL = /bin/sh

# Compiler
CC = g++

# Compiler flags
CFLAGS1 = -Wall

all:

clean:
	rm work1 work2 work3 work4 work5 work6 work7 work8

work1:
	$(CC) $(CFLAGS1) work1.cpp -o work1

work2:
	$(CC) $(CFLAGS1) work2.cpp -o work2

work3:
	$(CC) $(CFLAGS1) work3.cpp -o work3

work4:
	$(CC) $(CFLAGS1) work4.cpp -o work4

work5:
	$(CC) $(CFLAGS1) work5.cpp -o work5

work6:
	$(CC) $(CFLAGS1) work6.cpp -o work6

work7:
	$(CC) $(CFLAGS1) work7.cpp -o work7

work8:
	$(CC) $(CFLAGS1) work8.cpp -o work8
