SHELL = /bin/sh

# Compiler
CC = g++

# Compiler flags
CFLAGS = -Wall

all:

clean:
	rm work1 work2 work3 work4 work5 work6 work7 work8

work1:
	$(CC) $(CFLAGS) work1.cpp -o work1

work2:
	$(CC) $(CFLAGS) work2.cpp -o work2

work3:
	$(CC) $(CFLAGS) work3.cpp -o work3

work4:
	$(CC) $(CFLAGS) work4.cpp -o work4

work5:
	$(CC) $(CFLAGS) work5.cpp -o work5

work6:
	$(CC) $(CFLAGS) work6.cpp -o work6

work7:
	$(CC) $(CFLAGS) work7.cpp -o work7

work8:
	$(CC) $(CFLAGS) work8.cpp -o work8
