SHELL = /bin/sh

# Compiler
CC = g++

# Compiler flags
CFLAGS = -Wall

all:

clean:
	rm -f work1 work2 work3

work1:
	$(CC) $(CFLAGS) work1.cpp -o work1

work2:
	$(CC) $(CFLAGS) work2.cpp -o work2

work3:
	$(CC) $(CFLAGS) work3.cpp -o work3
