SHELL = /bin/sh

# Compiler
CC = g++

# Compiler flags
CFLAGS1 = -Wall

all:

clean:
	rm l4 l6 l7 l8 l9 l11 l12 l13 l14

l4:
	$(CC) $(CFLAGS1) l4.cpp -o l4

l6:
	$(CC) $(CFLAGS1) l6.cpp -o l6

l7:
	$(CC) $(CFLAGS1) l7.cpp -o l7

l8:
	$(CC) $(CFLAGS1) l8.cpp -o l8

l9:
	$(CC) $(CFLAGS1) l9.cpp -o l9

l11:
	$(CC) $(CFLAGS1) l11.cpp -o l11

l12:
	$(CC) $(CFLAGS1) l12.cpp -o l12

l13:
	$(CC) $(CFLAGS1) l13.cpp -o l13

l14:
	$(CC) $(CFLAGS1) l14.cpp -o l14
